name: Feature request
description: ✨ Suggest an feature or idea for the json formatter
title: "Feature Request: "
labels: enhancement

body:
- type: textarea
  attributes:
    label: Describe your feature
    description: A clear and concise description of your feature.
  validations:
    required: true
- type: textarea
  attributes:
    label: Any Solutions You have thought of?
    description: If you have a solution in your mind, you can decribe that here.
  validations:
    required: false
- type: textarea
  attributes:
    label: Additional context?
    description: |
      Add any other context or screenshots about the feature request here.

      Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
  validations:
    required: false
